project_id = "tjuunlzlspznabgldvjr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.bid-studio-ai]
    verify_jwt = false
  [functions.company-verification]
    verify_jwt = false
  [functions.draft-proposal]
    verify_jwt = false
  [functions.enrich-rfps]
    verify_jwt = false
  [functions.generate-ai-insights]
    verify_jwt = false
  [functions.process-agent-rfp]
    verify_jwt = false
  [functions.scrape-rfps]
    verify_jwt = false
